apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reverse-proxy-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "crystal-mev-proxy-ip"
spec:
  defaultBackend:
    service:
      name: nginx-tcp-np
      port:
        number: 80