steps:
- name: 'gcr.io/cloud-builders/kubectl'
  id: HDD volume
  args: ['apply', '-f', 'k8s/volumes, k8s/deployments, k8s/cluster-ip, k8s/load-balancers']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}'

timeout: 3600s
options:
  logging: CLOUD_LOGGING_ONLY

