steps:

- name: 'gcr.io/cloud-builders/kubectl'
  id: JWT secret
  entrypoint: bash
  args: [
    '-c',
    'envsubst "${$$GETH_JWT}"" < k8s/jwt-secret.yaml | kubectl apply -f -'
  ]
  secretEnv: ['GETH_JWT']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}'

- name: 'gcr.io/cloud-builders/kubectl'
  id: Apply claims
  args: ['apply', '-f', 'k8s/claims']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}'
 
- name: 'gcr.io/cloud-builders/kubectl'
  id: Apply deployments
  args: ['apply', '-f', 'k8s/deployments']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}'

- name: 'gcr.io/cloud-builders/kubectl'
  id: Apply cluster IPs
  args: ['apply', '-f', 'k8s/cluster-ip']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}'

- name: 'gcr.io/cloud-builders/kubectl'
  id: Apply node ports
  args: ['apply', '-f', 'k8s/node-ports']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}'

availableSecrets:
  secretManager:
  - versionName: projects/843423425535/secrets/GETH_JWT/versions/1
    env: 'GETH_JWT'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 3600s
