steps:
- name: 'gcr.io/cloud-builders/kubectl'
  id: Geth P2P LoadBalancer
  args: ['apply', '-f', 'k8s/geth-p2p-service.yaml']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}'

- name: 'gcr.io/cloud-builders/kubectl'
  id: Geth RPC service
  args: ['apply', '-f', 'k8s/geth-rpc-service.yaml']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}'

- name: 'gcr.io/cloud-builders/kubectl'
  id: Geth WebSocket service
  args: ['apply', '-f', 'k8s/geth-ws-service.yaml']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}'

- name: 'gcr.io/cloud-builders/kubectl'
  id: Geth node deployment
  args: ['apply', '-f', 'k8s/geth-deployment.yaml']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}'

timeout: 3600s
options:
  logging: CLOUD_LOGGING_ONLY

