steps:

- name: 'bhgedigital/envsubst'
  id: Secrets substitution
  entrypoint: /bin/sh
  args: [
    '-c',
    'envsubst < geth/config/jwt-secret.yaml > jwt-secret.yaml',
    'envsubst < geth/config/influxdb-secret.yaml > influxdb-secret.yaml'
    ]
  env:
    - 'GETH_AUTH_JWT=${_GETH_AUTH_JWT}'
    - 'INFLUX_DB_TOKEN=${_INFLUX_DB_TOKEN}'

- name: 'gcr.io/cloud-builders/kubectl'
  id: Apply JWT secret
  args: ['apply', '-f', 'jwt-secret.yaml']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}'

- name: 'gcr.io/cloud-builders/kubectl'
  id: Apply InfluxDB secret
  args: ['apply', '-f', 'influxdb-secret.yaml']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}'

- name: 'gcr.io/cloud-builders/kubectl'
  id: Apply influxdb
  args: ['apply', '-f', 'influxdb']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}'

- name: 'gcr.io/cloud-builders/kubectl'
  id: Apply geth claims
  args: ['apply', '-f', 'geth/claims']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}'
 
- name: 'gcr.io/cloud-builders/kubectl'
  id: Apply geth
  args: ['apply', '-f', 'geth/deployments']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}'

- name: 'gcr.io/cloud-builders/kubectl'
  id: Apply geth cluster IPs
  args: ['apply', '-f', 'geth/cluster-ip']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}'

- name: 'gcr.io/cloud-builders/kubectl'
  id: Apply geth node ports
  args: ['apply', '-f', 'geth/node-ports']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 3600s
