apiVersion: v1
kind: Service
metadata:
  name: geth-rpc-service
  labels:
    app: crystal-mev
spec:
  type: ClusterIP
  selector:
    app: crystal-mev
    comp: geth-node-pod
  ports:
  - name: rpc-endpoint
    port: 8545
    protocol: TCP
    targetPort: 8545