apiVersion: v1
kind: Service
metadata:
  name: geth-ws-service
  labels:
    app: crystal-mev
spec:
  type: ClusterIP
  selector:
    app: crystal-mev
    comp: geth-node-pod
  ports:
    - name: ws-endpoint
      port: 8546
      protocol: TCP
      targetPort: 8546