apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geth-node-ssd-volume
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  resources:
    limits:
      storage: 2Ti
  storageClassName: standard-rwo
