apiVersion: v1
kind: Service
metadata:
  name: foo
spec:
  ports:
  - port: 30303
    targetPort: 8080
    name: http 
  selector:
    app: foo
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
      - name: curl
        image: curlimages/curl
      - name: whereami
        image: us-docker.pkg.dev/google-samples/containers/gke/whereami:v1.2.11
        ports:
          - name: http
            containerPort: 8080
