apiVersion: v1
kind: Service
metadata:
  name: geth-execution-service
  labels:
    app: crystal-mev
spec:
  clusterIP: None # We create ah headless service, since geth node is a single pod
  selector:
    app: crystal-mev
    comp: geth-node-pod
  ports:
    - port: 8551
      protocol: TCP
      targetPort: 8551