apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geth-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    limits:
      storage: 400Gi # TODO: Upgrade quotas on gcloud
    requests: 
      storage: 50Gi
  storageClassName: premium-rwo
