apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geth-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    limits:
      storage: 2Ti 
    requests: 
      storage: 50Gi
  storageClassName: premium-rwo
