apiVersion: v1
kind: PersistentVolume
metadata:
  name: lighthouse-pv
  labels:
    app: crystal-mev
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: lighthouse-disk
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lighthouse-volume
  labels:
    app: crystal-mev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    limits:
      storage: 500Gi
    requests: 
      storage: 500Gi
  selector:
    matchLabels:
      app: crystal-mev
  storageClassName: pd-standard
