apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lighthouse-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    limits:
      storage: 128Gi
    requests: 
      storage: 10Gi
  storageClassName: standard-rwo
