apiVersion: v1
kind: PersistentVolume
metadata:
  name: ssd0-local-pv
  labels:
    app: crystal-mev
spec:
  capacity:
    storage: 1125Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/disks/ssd0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - gke-mev-cluster-default-pool-dd10e5c4-vjzg
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geth-volume
  labels:
    app: crystal-mev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    limits:
      storage: 1125Gi 
    requests: 
      storage: 1125Gi 
  selector:
    matchLabels:
      app: crystal-mev
  storageClassName: local-storage