apiVersion: v1
kind: Service
metadata:
  name: eth-node-l1-lb
  labels:
    app: crystal-mev
    comp: geth-p2p-tcp-lb
spec:
  type: LoadBalancer
  selector:
    app: crystal-mev
  loadBalancerIP: 34.123.192.239
  ports:
    - name: p2p-tcp-l1-lb
      port: 30303
      protocol: TCP
      targetPort: p2p-tcp-lb
