apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lighthouse-claim
  labels:
    app: crystal-mev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: premium-rwo
  resources:
    limits:
      storage: 500Gi 
    requests: 
      storage: 500Gi 
