steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build nginx image
  entrypoint: 'bash'
  args: [
    '-c',
    'docker build -t gcr.io/$PROJECT_ID/crystal-mev-nginx:$COMMIT_SHA 
    --build-arg AUTH_USERNAME=$$AUTH_USERNAME
    --build-arg AUTH_PASSWORD=$$AUTH_PASSWORD 
    .'
  ]
  secretEnv: ['AUTH_USERNAME', 'AUTH_PASSWORD']

- name: 'gcr.io/cloud-builders/docker'
  id: Push nginx image to registry
  args: ['push', 'gcr.io/$PROJECT_ID/crystal-mev-nginx:$COMMIT_SHA']

- name: 'gcr.io/cloud-builders/kubectl'
  id: Apply definitions
  args: ['apply', '-f', 'k8s']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}' 

- name: 'gcr.io/cloud-builders/kubectl'
  id: Set nginx deployment image
  args:
    [
     'set',
     'image',
     'deployment',
     'nginx-deployment',
     'crystal-mev-nginx=gcr.io/$PROJECT_ID/crystal-mev-nginx:$COMMIT_SHA'
     ]
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}' 

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/AUTH_USERNAME/versions/1
      env: 'AUTH_USERNAME'
    - versionName: projects/$PROJECT_ID/secrets/AUTH_PASSWORD/versions/1
      env: 'AUTH_PASSWORD'
timeout: 3600s
