apiVersion: v1
kind: Service
metadata:
  name: lighthouse-beacon-tcp-np
  labels:
    app: crystal-mev
    comp: lighthouse-beacon-tcp-np
spec:
  type: NodePort
  selector:
    app: crystal-mev
    comp: lighthouse-pod
  ports:
    - name: beacon-tcp-np
      port: 9000
      protocol: TCP
      targetPort: beacon-port-tcp
