apiVersion: apps/v1
kind: Deployment
metadata:
  name: geth-deployment
  labels:
    app: crystal-mev
spec:
  selector:
    matchLabels:
      app: crystal-mev
      comp: geth-node-pod
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: crystal-mev
        comp: geth-node-pod
    spec:
      nodeSelector:
        cloud.google.com/compute-class: "Balanced"
      containers:
        - name: geth-node-pod
          image: ethereum/client-go:stable
          args: 
            - "--mainnet"
            - "--datadir=/var/geth"
            - "--authrpc.addr=0.0.0.0"
            - "--authrpc.port=8551"
            - "--authrpc.vhosts=*"
            - "--authrpc.jwtsecret=/etc/jwt/jwtsecret"
            - "--ws"
            - "--ws.api=txpool,eth,net,web3,personal"
            - "--ws.origins=*"
            - "--http"
            - "--http.api=txpool,eth,net,web3,personal"
            - "--http.corsdomain=*"
            - "--http.vhosts=*"
            - "--syncmode=full"
          resources:
            limits:
              cpu: 4000m
              memory: 16Gi
            requests:
              cpu: 1500m
              memory: 4Gi
          ports:
            - containerPort: 8545
              name: rpc-port
            - containerPort: 8546
              name: ws-port
            - containerPort: 30303
              name: p2p-port-udp
              protocol: UDP
            - containerPort: 30303
              name: p2p-port-tcp
              protocol: TCP
            - containerPort: 8551
              name: exec-port-tcp
              protocol: TCP
          startupProbe:
            tcpSocket:
              port: 8551
            failureThreshold: 30 # 5 minutes (30 * 10 = 300s) to finish startup
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8551
            initialDelaySeconds: 15
            timeoutSeconds: 5
          volumeMounts:
            - mountPath: "/var/geth/"
              name: geth-volume
            - mountPath: /etc/jwt/
              name: jwt-config
      volumes:
        - name: geth-volume
          persistentVolumeClaim:
            claimName: geth-volume
        - name: jwt-config
          configMap:
            name: jwt-config

