apiVersion: v1
kind: Service
metadata:
  name: geth-p2p-tcp-lb
  labels:
    app: crystal-mev
spec:
  type: LoadBalancer
  selector:
    app: crystal-mev
  loadBalancerIP: 34.123.192.239
  ports:
    - name: p2p-tcp-lb
      port: 30303
      protocol: TCP
      targetPort: p2p-tcp-np
