apiVersion: v1
kind: Service
metadata:
  name: lighthouse-beacon-udp-lb
  labels:
    app: crystal-mev
spec:
  type: LoadBalancer
  selector:
    app: crystal-mev
    comp: lighthouse-pod
  ports:
    - name: beacon-udp-lb
      port: 9000
      protocol: UDP
      targetPort: beacon-port-udp
