apiVersion: v1
kind: Service
metadata:
  name: lighthouse-beacon-tcp-service
  labels:
    app: crystal-mev
spec:
  type: NodePort
  selector:
    app: crystal-mev
    comp: lighthouse-pod
  ports:
    - name: beacon-tcp-endpoint
      port: 9000
      protocol: TCP
      targetPort: 9000
