apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geth-claim
  labels:
    app: crystal-mev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: premium-rwo
  resources:
    limits:
      storage: 2000Gi 
    requests: 
      storage: 2000Gi 
